### ISSUE TITLE
Any plans to include HI-MD coded music?

### ISSUE THREAD

**Issue by Seeker000** [gavinbenda/platinum-md#40] opened 2020-05-29 16:09 UTC
I'm very excited to see your efforts to keep the minidisc format alive.

Do you have any plans to include the HI-MD format? All of my music is HI-MD.

Thanks in advance.

Kevin Siddons

**Comment by Invictaz** [comment] 2020-05-29 16:23
Duplicate of #8

**Comment by gavinbenda** [comment] 2020-05-31 03:06
There is some work being done by the linux-minidisc project on Hi-MD - at the moment there isn't a method to transfer quite yet as it involves some quite niche (and complex) maths around encryption and compression.

**Closed by gavinbenda** 2020-05-31 03:06 UTC
Labels: duplicate
